version: '3'
services:
  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    networks:
      - bank-network
  account-service:
    build:
      context: ./account-service
    ports:
      - "8081:8081"
    networks:
      - bank-network

  transaction-service:
    build:
      context: ./transaction-service
    ports:
      - "8082:8082"
    networks:
      - bank-network

networks:
  bank-network:
